version: 1

disable_existing_loggers: false

formatters:
  basic:
    format: "%(asctime)s %(levelname)-8s %(module)-18s %(funcName)-10s %(lineno)4d: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: basic
    stream: ext://sys.stdout

loggers:
  app:
    level: DEBUG
    handlers: [console]
    propagate: no

root:
  level: DEBUG
  handlers: [console]
